### ISSUE TITLE
e4mc in modpacks

### ISSUE THREAD

**Issue by Rebel459** [blryface/notessential#10]
Hi there! A suggestion I had for the site was to add a small note / disclaimer somewhere saying that e4mc is recommended for modpacks - in my experience (admittedly half a year ago, but across 3 varying-size modpacks on different modloaders), World Host has some weird stability issues, whereas I've only ever had a flawless experience with e4mc

While I'm here, though not important I also thought I'd add that the site is blocked/marked as suspicious by Norton 360, though I'm not opening an issue for this as it's relatively minor and the antivirus' fault

**Comment by KTrain5169** [comment]
> While I'm here, though not important I also thought I'd add that the site is blocked/marked as suspicious by Norton 360, though I'm not opening an issue for this as it's relatively minor and the antivirus' fault

antivirus moment
Might be due to the high amount of links in the alternatives page but idk
