### ISSUE TITLE
add skin shuffle as an alternative to the essential mod skin swaper

### ISSUE THREAD

**Issue by Thinkseal** [blryface/notessential#15]
link to it 
[https://modrinth.com/mod/skinshuffle](https://modrinth.com/mod/skinshuffle)

**Comment by blryface** [comment]
THERES A SKIN SWAPPER IN ESSENTIAL??

**Comment by Thinkseal** [comment]
Yes it is in the cosmetics menu

**Comment by KTrain5169** [comment]
> THERES A SKIN SWAPPER IN ESSENTIAL??

lmao you didn't know
tbf it's integrated as part of the wardrobe

**Comment by KTrain5169** [comment]
Anyways I'll get that sorted rq

**Comment by KTrain5169** [comment]
Closed #15 as completed in #17 & 57457a3
