### ISSUE TITLE
GitHub Action to check commits and PRs if they were formatted with Prettier

### ISSUE THREAD

**Issue by Nitrrine** [blryface/notessential#22]
This will be really useful feature as both maintainers and contributors can check if their code was formatted with Prettier and fix the formatting before merging to the production.

**Comment by KTrain5169** [comment]
Would be very nice to have, if you don't already have something in mind then I'll do something as well

**Comment by KTrain5169** [comment]
c0bd240 & b1d31a6 should have made a workflow, not sure how to test if it works 🤔

**Comment by Nitrrine** [comment]
> [c0bd240](https://github.com/blryface/notessential/commit/c0bd24007ff795d1fdfc80b2db6568c1ea1d3e9f) & [b1d31a6](https://github.com/blryface/notessential/commit/b1d31a6a274ef16df6fa82c2ab2e2222bbedfed6) should have made a workflow, not sure how to test if it works 🤔

I assigned issue to myself because i wanted to implement it 😭

**Comment by KTrain5169** [comment]
> > [c0bd240](https://github.com/blryface/notessential/commit/c0bd24007ff795d1fdfc80b2db6568c1ea1d3e9f) & [b1d31a6](https://github.com/blryface/notessential/commit/b1d31a6a274ef16df6fa82c2ab2e2222bbedfed6) should have made a workflow, not sure how to test if it works 🤔
> 
> I assigned issue to myself because i wanted to implement it 😭

goddamn it
