### ISSUE TITLE
Homepage animation loops improperly on Firefox-based browsers

### ISSUE THREAD

**Issue by HyperSoop** [blryface/notessential#29]
## Describe the bug here

The moving stripe on the homepage of the site seems to loop improperly, causing some text on the left side of the screen to disappear once in a while

## Steps to reproduce

Step 1: Visit https://notessential.blurryface.xyz/
Step 2: Wait 20 seconds or so

## Expected result

The animation loops seamlessly (no text ever just pops out of existence)

### Additional info

![image](https://github.com/blryface/notessential/assets/85982640/902ce43a-61c3-40b8-804e-ce121eb77bc5)
![image](https://github.com/blryface/notessential/assets/85982640/ffc429cf-3785-4221-9899-c58007d50916)
uBO doesn't block anything on the page.

## Checklist

- [x] I have clearly and, to the best of my ability, accurately stated info about the bug I'm experiencing.
- [x] I have searched for duplicate issues and have not found any.
- [ ] I did not read this section.

**Comment by HyperSoop** [comment]
https://github.com/blryface/notessential/assets/85982640/a87dec9e-ed20-449a-9e7d-0c2d42029595

**Comment by KTrain5169** [comment]
I assume this is Firefox?

**Comment by worldwidepixel** [comment]
I created this animation and only tested it on Google Chrome. I'll try recreating on Firefox.

**Comment by blryface** [comment]
Can confir, happens on FireFox. I  assume it has something to do with the position it decides to start on it

**Comment by worldwidepixel** [comment]
I'll try a Node-provided 'slider module' to hopefully get a more consistent result.

**Comment by Nitrrine** [comment]
Should be fixed by 4c03226
