### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by blryface** [blryface/notessential#30]
We should try to support multiple languages for the website so it's accessible to more people. Ideally, we should use Crowdin for translations rather than forks and PRs, because it's just nicer to do that way.

I can do the Brazilian translations right away to test if the options work, and then we can add it to Crowdin

**Comment by worldwidepixel** [comment]
I can try to work i18n compatibility into the site; JSON-based alternatives should already make that process much simpler

**Comment by worldwidepixel** [comment]
Compatibility added!
