### ISSUE TITLE
[POLL] Include CurseForge download links?

### ISSUE THREAD

**Issue by KTrain5169** [blryface/notessential#35]
[This discussion](https://discord.com/channels/734077874708938864/783091855616901200/1261926428388102195) started the train of thought of "Do we allow CurseForge links as a download source?"

These are the reasons why we would want to include CurseForge as an option:
* Big platform. This means that many mods may be locked behind it.
* Direct integration with the CurseForge App for the 5 people who use it.
* Many people are more familiar with it and are more likely to trust it.

And these are the reasons why we would want to not include CurseForge as an option:
* Malware issues. It's not just "malware can run rampant" because literally any platform like CurseForge and Modrinth can have this happen to them. But their staff when it comes to dealing with this... bruh.
* Terrible UI. There's a reason why Sodium & Iris left the platform, and many more followed. Ads are also intrusive which doesn't help it any further.
* CurseForge is also very known to take down stuff for no reason (though most notably when Sodium left CurseForge) and their antivirus checks aren't the sharpest tool in the shed but they do rely on it too much.

👍 for yes, 👎 for no, first person for each option has to add it manually.
When this issue is closed, so will the poll.

side bonus:
![image](https://github.com/user-attachments/assets/932b3122-3b51-4acd-bc00-32ff8a2ee2c5)

**Comment by worldwidepixel** [comment]
Curseforge download links are already possible. I designed the data-driven alternatives page with more than one link in mind.

**Comment by KTrain5169** [comment]
> Curseforge download links are already possible. I designed the data-driven alternatives page with more than one link in mind.

Yes, but we've had a tendency to avoid CurseForge because of how terrible it is compared to Modrinth and that so many mods are on Modrinth anyways.

**Comment by worldwidepixel** [comment]
I think including Curseforge based on the author's wishes is best. If they clearly despise it, don't include it.

**Comment by blryface** [comment]
There's hardly any good open source mod that is on curse, and it's much more of a pain to use curse for a few reasons, such as:
- Updates need time to be approved by moderators
- The content may be unavailable to 3rd party launchers
- "STILL DOWNLOADING MANUALLY??"

**Comment by worldwidepixel** [comment]
It goes down to the mod creator's wishes. If a great ess. alternative is also on Curseforge and adds their curse link, I think it's best to respect their wishes

**Comment by Andre601** [comment]
An argument I give against CF is their lack of support in regards to taking down projects that were uploaded without the original owner's permission, while also violating the project's license...
Reported a project 3 times - once directly to their support through e-mail - and it still is present, misleading people as they think it's the latest version and official...

**Comment by KTrain5169** [comment]
The issue is now closed because I think there's a clear consensus regarding this.
