### ISSUE TITLE
Fix - Change site URL

### ISSUE THREAD

**Issue by KTrain5169** [blryface/notessential#39]
Currently, the blurryface.xyz domain died, so we've migrated over to notessential.blurry.gay

@blryface please update the link in the sidebar on the main page

**Comment by blryface** [comment]
Does this need to be an issue just @ me on discord

**Comment by intergrav** [comment]
> Does this need to be an issue just @ me on discord

Generally I do think it’s a good idea to make an issue for things no matter how small the issue is, so that it’s easier to keep track of and remember
