### ISSUE TITLE
add ZUME as alternative for essential zoom feature

### ISSUE THREAD

**Issue by cutiegin** [blryface/notessential#6]

**Comment by blryface** [comment]
why exactly ZUME?

**Comment by cutiegin** [comment]
> why exactly ZUME?

zume is for all versions. b1.7.3 to 1.21

**Comment by blryface** [comment]
Oh interesting, I'll add it when I get home then!

**Comment by KTrain5169** [comment]
Essential had a zoom feature? since when?? Anyways I'll PR it since blryface forgor

**Comment by blryface** [comment]
> Essential had a zoom feature? since when?? Anyways I'll PR it since blryface forgor

since really early on
