### ISSUE TITLE
Include Figura for cosmetic/custom model stuff

### ISSUE THREAD

**Issue by Andre601** [blryface/notessential#7]

**Comment by KTrain5169** [comment]
Could you explain why this mod should be added?

**Comment by Andre601** [comment]
Because it's a cosmetic/custom player model mod on steroids?

Like... You can customize your character, and thanks to lua scripting support even customize stuff like what parts to render, when to render, animations to play, etc.

Like, here is an example of my own skin with a custom right arm, fox tail that also wags, and a small fox resting on my head that may look around or take a nap at random intervals:

https://github.com/blryface/notessential/assets/11576465/6a412de8-c1b0-4b18-94d3-9088b33272ba

Suggesting CPM but not Figure is really weird in all honesty.

**Comment by KTrain5169** [comment]
You haven’t gone home in days dude I swear

Also, I did say I was going to reuse the branch in #8 for this issue as well, right? I’ll get around to that in a sec

Grab Outlook for iOS<https://outlook.live.com/>
________________________________

**Comment by blryface** [comment]
I got home and got distracted and forgot
Blame my meds, I can barely think or retain memory during ~1PM-6PM

Em seg., 24 de jun. de 2024, 19:07, KTrain ***@***.***>
escreveu:

**Comment by blryface** [comment]
Why does replying to the email add a timestamp

**Comment by KTrain5169** [comment]
How do you edit via email

**Comment by KTrain5169** [comment]
> Why does replying to the email add a timestamp

Probably because it includes such in a typical email reply

**Comment by KTrain5169** [comment]
Fixed in #8
